apiVersion: apps/v1
kind: Deployment
metadata:
  name: shpd-bot
  labels:
    app: shpd-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shpd-bot
  template:
    metadata:
      labels:
        app: shpd-bot
    spec:
      containers:
        - name: shpd-bot
          image: shpd-bot:1.0.0 
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/shpd_db"
          # Si quieres sobreescribir el token de Telegram, puedes descomentar y ajustar:
          # - name: TELEGRAM_TOKEN
          #   valueFrom:
          #     secretKeyRef:
          #       name: bot-secret
          #       key: token
          ports:
            - containerPort: 80   # ajusta si tu bot expone algún puerto HTTP
